### ISSUE TITLE
couldn't publish to sonatype with github actions

### ISSUE THREAD

**Issue by oshai** [gradle-nexus/publish-plugin#130]
I am trying to move to github actions from travis.
At the moment, release fails with http error 401:
![image](https://user-images.githubusercontent.com/2683969/143659175-3671efba-1ac0-4d1a-adf4-f731e71048ab.png)
here: https://github.com/jasync-sql/jasync-sql/runs/4338041857?check_suite_focus=true

I configured env vars for branch: 
![image](https://user-images.githubusercontent.com/2683969/143659223-032036fa-eff4-4b20-84ea-f169f4c48317.png)
And the action have those env var defined:
```
env:
            ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
            ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
            ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
            ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
```

Is there a way to validate what token being send to sonatype?
