### ISSUE TITLE
E2E tests for side branches should be executed only if requested

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#181]
The E2E tests are currently executed for:
```
on:
  schedule:
    - cron: "0 6 * * MON"
  push:
    branches:
      - master
      - "szpak/**"
      - "marc/**"
```

With the majority of small fixing commits within a PR, it is not needed to engage the (usually hard working) Sonatype Nexus. It would be probably better to limit to:
 - cron
 - master
 - e2e/** - e.g. branch created from pull request branch for "cross-sectional" changes
 - when requested via `[perform e2e]` in the commit message (only for local branches)

Instead of `e2e/**` it would be better to manually approve from UI the e2e workflow for particular commit in the particular PR, but I don't if it is possible with GH Actions.

WDYT?
